# Generated by Django 3.2.9 on 2021-11-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producat_image',
            new_name='product_image',
        ),
    ]
